[360] https://atcoder.jp/contests/abc360/tasks
daiichiii/Atcorder-Review pull request #1
Opened 2024-07-02 23:11 UTC by daiichiii

Atcoder360番のABC問題です。

2024-07-02 23:25 UTC, motoharuinoue requested changes

2024-07-02 23:25 UTC, motoharuinoue commented on Atcoder_#360/A Healthy Breakfast.rb
まず、ファイル名にこだわりましょう。
rubyのファイル名のスタンダードな命名規則を勉強してください。

rubyのファイル名がスネークケースではないことに違和感があるし、
特に、ファイル名に空白があるとか、普通言語道断なので。

2024-07-02 23:25 UTC, motoharuinoue commented on Atcoder_#360/C - Move It.rb
> +end
ここ多分、まとめて書けると思うよ

2024-07-03 15:48 UTC, daiichiii commented on Atcoder_#360/A Healthy Breakfast.rb
ありがとうございます。

こちら全く何も考えずにファイル名を記載しておりました。
以下のコミットで修正いたしました！

2024-07-03 16:02 UTC, daiichiii commented on Atcoder_#360/C - Move It.rb
> +end
申し訳ございません。
まとめる方法と理由が、あまり理解できていないため、
教えて頂きたいです。

自分としては、
初期化する処理と配列に値を追加する処理は分けた方が、
責務が分かれていて、良いのでは？と考えております。

2024-07-04 21:57 UTC, merged

2024-07-06 09:38 UTC, motoharuinoue commented on Atcoder_#360/C - Move It.rb
> +end
each_with_object と with_index 使ったらもう少し簡潔に書けるかなと思ったんだけど、
この2つ、同時に使えないらしいから、これでいいか